name: Push a main
on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  test:
    name: Ejecutar pruebas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'

      - name: Instalar pnpm
        run: |
          npm install --global corepack@latest
          corepack enable pnpm          

      - name: Instalar dependencias
        run: pnpm install

      - name: Ejecutar tests
        run: pnpm test --silent --coverage

      - name: Post failure to Slack
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "*Push a `${{ github.ref_name }}`*\n\n ❌ *Fallaron los tests en* `${{ github.repository }}`\n\n*Commit:* `${{ github.event.head_commit.id }}` ${{ github.event.head_commit.message }}"
            attachments: [
              {
                "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Ver logs de la ejecucion>"
              }
            ]
  
  
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Instalar pnpm
        run: |
          npm install --global corepack@latest
          corepack enable pnpm          

      - name: Instalar dependencias
        run: pnpm install

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  
  deploy:
    runs-on: ubuntu-latest
    # environment: staging
    timeout-minutes: 60
    needs: [test, sonarqube] #Para desplegar necesito que los jobs anteriores terminen con exito.

    outputs:
      deployment-url: ${{ steps.deploy.outputs.deployment-url }}
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar pnpm
        run: |
          npm install --global corepack@latest
          corepack enable pnpm  
        
      - name: Build & Deploy Worker
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4.16.1"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env staging #Despliega en staging

      - name: Post success to Slack
        if: success()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "🚀 *Deploy exitoso a `staging`* desde `${{ github.repository }}`\n\n*Commit:* `${{ github.event.head_commit.id }}` ${{ github.event.head_commit.message }}"
            attachments: [
              {
                "text": "<${{ steps.deploy.outputs.deployment-url }}|Visitar el sitio desplegado>"
              }
            ]

      - name: Post failure to Slack
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "❌ *Fallo el deploy a `staging`* en `${{ github.repository }}`\n\n*Commit:* `${{ github.event.head_commit.id }}` ${{ github.event.head_commit.message }}"
            attachments: [
              {
                "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Ver logs de la ejecucion>"
              }
            ]

      - name: Crear Deployment en GitHub
        uses: bobheadxi/deployments@v1
        id: creardeploy
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: staging
          ref: ${{ github.sha }}
      
      - name: Marcar Deployment como exitoso
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: staging
          status: success
          deployment_id: ${{ steps.creardeploy.outputs.deployment_id }}
          env_url: ${{ steps.deploy.outputs.deployment-url }}

  lighthouse:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Lighthouse CI Slack Reporter
        uses: MateuszMichalowski/lhci-slack-reporter@v1.0.4
        with:
          # Comma-separated list of URLs to test
          urls: ${{ needs.deploy.outputs.deployment-url }}
          # Slack channel to send the report to (without #)
          slack_channel: ${{ secrets.SLACK_CHANNEL_ID }}
          # Slack API token (required if slack_webhook_url is not provided)
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          # Title for the Slack message
          slack_title: Resultados de Lighthouse
