name: Ejecutar pruebas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ejecutar-pruebas:
    name: Ejecutar pruebas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'

      - name: Instalar pnpm
        run: |
          npm install --global corepack@latest
          corepack enable pnpm

      - name: Cache pnpm
        uses: actions/cache@v4.2.3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-            

      - name: Instalar dependencias
        run: pnpm install

      - name: Ejecutar tests
        run: pnpm test
