name: Trello
on:
  pull_request:
    types: [opened, edited, closed, reopened, ready_for_review, converted_to_draft]

permissions:
  pull-requests: write
  contents: read

jobs:
  trello:
    runs-on: ubuntu-latest
    steps:
      - uses: rematocorp/trello-integration-action@v9.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          trello-api-key: ${{ secrets.TRELLO_API_KEY }}
          trello-auth-token: ${{ secrets.TRELLO_AUTH_TOKEN }}
          trello-list-id-pr-open: ${{ env.TRELLO_DOING_LIST_ID }}
          trello-list-id-pr-merged: ${{ env.TRELLO_DONE_LIST_ID }}
          github-include-pr-commit-messages: true
